### ISSUE TITLE
Toggleable buildings should stop consuming materials after their produced resource is at its cap

### ISSUE THREAD

**Issue by Raketemensch23** [Morpheox/Kraft#71]
I notice that toggleable buildings which produce resources with a storage cap stop producing more after that cap is hit, but they still consume resources.  I noticed this behavior with pastures, foundries, kilns, crushers, and laboratories.

Shouldn't a resource quit consuming resources if it can't produce any more of its production resource?

**Comment by Morpheox** [comment]
Its on purpose, imagine if a building produces two different resources and one hits the cap, should that also stop producing and consuming?
You can always switch the building off.  If you have it on, i imagine it as producing, but going to waste because you dont any have space left to storage it.
I might rethink it in the future, but its intentional the way it is now, so i will close this issue.
